- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: nodejs setup
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs

- name: systemd setup
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd